name: QueueForge CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  backend:
    name: Backend Check
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/test

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: TypeScript check
        run: npx tsc --noEmit


  worker:
    name: Worker Check
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/test

    defaults:
      run:
        working-directory: worker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: worker/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: TypeScript check
        run: npx tsc --noEmit


  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build